version: 2.1

jobs:
 build:
   machine:
    image: ubuntu-2004:current
   resource_class: arm.medium
   steps:
     - checkout
     - run: |
         echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
     - run: docker build -t erikd256/stfranciscusheverlee:latest --platform linux/arm64 .

     # deploy the image
     - run: docker push erikd256/stfranciscusheverlee:latest

workflows:
  build-docker-image:
    jobs:
      - build