query pageQuery {
  ...LayoutQueryFragment
  postConnection(sort: "date", last: -1) {
    edges {
      node {
        id
        _values
        author {
          ... on Author {
            ...AuthorParts
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query weeknieuwsQuery {
  ...LayoutQueryFragment
  weeknieuwsConnection(sort: "date", last: -1) {
    edges {
      node {
        id
        _values
        _sys {
          filename
        }
      }
    }
  }
}

query blogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    ...PostParts
    author {
      ... on Author {
        name
        avatar
      }
    }
  }
}
